//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oscar.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Oscar.Data.SqlResources", typeof(SqlResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = &apos;IX_Rights_ClientId_CatalogueId_TypeId&apos; AND object_id = OBJECT_ID(&apos;dbo.Rights&apos;))
        ///BEGIN
        ///    CREATE NONCLUSTERED INDEX [IX_Rights_ClientId_CatalogueId_TypeId] 
        ///    ON [dbo].[Rights] ([ClientId], [CatalogueId], [TypeId]) 
        ///    WITH (ONLINE = ON);
        ///END;
        ///GO
        ///IF NOT EXISTS (SELECT 1    FROM sys.indexes WHERE name = &apos;IX_Rights_WorksId_TypeId&apos; AND object_id = OBJECT_ID(&apos;dbo.Rights&apos;))
        ///BEGIN
        ///    CREATE NONCLUSTERED INDEX IX_Rights_WorksId_TypeId 
        ///    ON dbo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Indexes {
            get {
                return ResourceManager.GetString("Indexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR ALTER PROCEDURE [dbo].[sp_DeleteImportedWorks]
        ///(
        ///	@WorksImportRequestId INT
        ///) 
        ///AS 
        ///BEGIN
        ///    -- Drop temporary table if exists
        ///    DROP TABLE IF EXISTS #tempWorksToBeDeleted;
        ///
        ///    -- Create temporary table
        ///    CREATE TABLE #tempWorksToBeDeleted
        ///    (
        ///        WorksId INT
        ///    );
        ///
        ///    -- Clear temporary table
        ///    DELETE FROM #tempWorksToBeDeleted;
        ///
        ///    -- Insert relevant Works IDs into temporary table
        ///    INSERT INTO #tempWorksToBeDeleted (WorksId)
        ///    SELECT id 
        ///    FROM Works w [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sp_DeleteImportedWorks {
            get {
                return ResourceManager.GetString("sp_DeleteImportedWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR ALTER PROCEDURE [dbo].[sp_GetClientCatalogueSocietyWorks]
        ///(
        ///	@ClientId INT = NULL,
        ///	@CatalogueId INT = NULL,
        ///	@SocietyId INT,
        ///	@IncludePreviouslyRegistered BIT
        ///)AS 
        ///BEGIN
        ///    DECLARE @WorksId INT;
        ///
        ///    DROP TABLE IF EXISTS #tempworks
        ///    CREATE TABLE #tempworks (worksid INT,
        ///    parentworksid INT,
        ///    discriminator VARCHAR(50),
        ///	catalogueId INT)
        ///
        ///	--Insert Series and StandAlones
        ///    INSERT INTO #tempworks(worksid, parentworksid, discriminator, catalogueId)
        ///    SELECT DISTINCT w.i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sp_GetClientCatalogueSocietyWorks {
            get {
                return ResourceManager.GetString("sp_GetClientCatalogueSocietyWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR ALTER PROCEDURE sp_GetClientWorkProductionYearlyStats
        ///	@CurrentYear INT,
        ///    @ClientId INT = NULL  -- Optional parameter with default value NULL
        ///AS
        ///BEGIN
        ///    DECLARE @Sql NVARCHAR(MAX)
        ///
        ///    SET @Sql = N&apos;
        ///    SELECT 
        ///        ClientId,
        ///        ClientName as Client,
        ///        ClientGrade as Grade,
        ///        AccountManager as CSM,
        ///        ClientStatus as Status,
        ///        --MAX(CASE WHEN ProductionYear = &apos; + CAST(@CurrentYear AS NVARCHAR(4)) + &apos; THEN ProductionYear END) AS [&apos; + CAST(@CurrentYe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sp_GetClientWorkProductionYearlyStats {
            get {
                return ResourceManager.GetString("sp_GetClientWorkProductionYearlyStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR ALTER PROCEDURE sp_GetClientWorkYearlyStats
        ///	@CurrentYear INT,
        ///    @ClientId INT = NULL  -- Optional parameter with default value NULL
        ///AS
        ///BEGIN
        ///    DECLARE @Sql NVARCHAR(MAX)
        ///
        ///    SET @Sql = N&apos;
        ///    SELECT 
        ///        ClientId,
        ///        ClientName as Client,
        ///        ClientGrade as Grade,
        ///        AccountManager as CSM,
        ///        ClientStatus as Status,
        ///        ISNULL(MAX(CASE WHEN CreatedYear = &apos; + CAST(@CurrentYear AS NVARCHAR(4)) + &apos; THEN Episodes END), 0) AS [&apos; + CAST(@CurrentYear AS NVAR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sp_GetClientWorkYearlyStats {
            get {
                return ResourceManager.GetString("sp_GetClientWorkYearlyStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR ALTER PROCEDURE [dbo].[sp_GetWorksTitleByTitle]
        ///    @Title NVARCHAR(255),
        ///    @SearchType NVARCHAR(50)
        ///AS
        ///BEGIN
        ///    DECLARE @SearchPattern NVARCHAR(255)
        ///
        ///    SET @SearchPattern = CASE
        ///        WHEN @SearchType = &apos;StartsWith&apos; THEN @Title + &apos;%&apos;
        ///        WHEN @SearchType = &apos;Contains&apos; THEN &apos;%&apos; + @Title + &apos;%&apos;
        ///        WHEN @SearchType = &apos;Equals&apos; THEN @Title
        ///    END
        ///
        ///    IF @SearchType = &apos;FreeText&apos;
        ///    BEGIN
        ///        SELECT wt.Id, wt.WorksId, wt.Title, wt.TitleType
        ///        FROM WorksTitle wt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sp_GetWorksTitleByTitle {
            get {
                return ResourceManager.GetString("sp_GetWorksTitleByTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER VIEW [dbo].[vw_OnMusic_Felix_Works]
        ///AS
        ///select c.id as ClientsId, 
        ///cat.Id as CataloguesId, 
        ///c.ClientName ,
        ///cat.Name as CatalogueName,
        ///w.id as WorksId,
        ///w.AgicoaWorksReference as WorksReference,
        ///ISNULL(w.AS400RefNo, &apos;&apos;) AS AS400RefNo, 
        ///CASE WHEN w.Discriminator = &apos;Episode&apos; THEN w.Number ELSE 0 END AS EpisodeRef,
        ///CASE WHEN W.Discriminator = &apos;StandAlone&apos; THEN 0 WHEN w.Discriminator = &apos;Series&apos;  THEN 1 WHEN w.Discriminator = &apos;Season&apos; THEN 2 WHEN w.Discriminator = &apos;Episode&apos; THEN 3 END AS SerialLevel [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string V_AlterClientWorksList {
            get {
                return ResourceManager.GetString("V_AlterClientWorksList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR ALTER VIEW [dbo].[V_ClientCataloguesDetails] AS
        /// WITH ContactDetails AS
        /// (
        ///	Select ROW_NUMBER() OVER (PARTITION BY ClientId,CatalogueId ORDER BY Id) as RowNum, 
        ///		   c.ClientId, c.CatalogueId,
        ///		   c.Salutation, c.Title, c.FirstName, c.LastName, 
        ///		   c.Email, c.JobTitle, c.Mobile, c.PeriodStart, c.PeriodEnd, 
        ///		   c.Type, c.CreationDate, c.Website --, c.Commentss		   
        ///	  From dbo.Contact c
        ///	 Where c.ClientId IS NOT NULL
        /// )
        /// select distinct
        ///		cl.Id as ClientId, cl.ClientName, 
        ///		case  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string V_ClientCataloguesDetails {
            get {
                return ResourceManager.GetString("V_ClientCataloguesDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR ALTER VIEW [dbo].[V_ClientDetails] AS
        /// WITH ContactDetails AS
        /// (
        ///	Select ROW_NUMBER() OVER (PARTITION BY ClientId ORDER BY Id) as RowNum, c.ClientId,
        ///		   c.Salutation, c.Title, c.FirstName, c.LastName, 
        ///		   c.Email, c.JobTitle, c.Mobile, c.PeriodStart, c.PeriodEnd, 
        ///		   c.Type, c.CreationDate, c.Website --, c.Commentss		   
        ///	  From dbo.Contact c
        ///	 Where c.ClientId IS NOT NULL
        /// )
        /// select distinct
        ///		cl.Id as ClientId, cl.ClientName, 
        ///		case cl.Status
        ///			when 1 then &apos;Active In Term&apos;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string V_ClientDetails {
            get {
                return ResourceManager.GetString("V_ClientDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR ALTER VIEW [dbo].[V_ClientProductionCountries] AS
        /// select distinct 
        ///		w.Id as WorksId,
        ///		cl.Id as ClientId,	cl.ClientName, ct.Id as CatalogueId, ct.Name as CatalogueName,
        ///		(select STRING_AGG(wt1.Title, &apos;, &apos;) from WorksTitle wt1 where wt1.TitleType IN(1,2) and wt1.WorksId = w.Id) as Title, 
        ///		(select STRING_AGG(wt2.Title, &apos;, &apos;) from WorksTitle wt2 where wt2.TitleType IN(3,4) and wt2.WorksId = w.Id) as AlternateTitle,
        ///		w.CompactRef, w.Discriminator, 
        ///		(select STRING_AGG(c.Name,&apos;, &apos;) from C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string V_ClientProductionCountries {
            get {
                return ResourceManager.GetString("V_ClientProductionCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR ALTER VIEW [dbo].[V_ClientWorkListOfRights] AS
        ///	select distinct
        ///		   cl.Id as ClientId, cl.ClientName, ct.Id as CatalogueId, ct.Name as CatalogueName,
        ///		   w.Id as WorksId, w.Discriminator, 
        ///		   (select STRING_AGG(wt1.Title, &apos;, &apos;) from WorksTitle wt1 where wt1.WorksId = w.Id and wt1.TitleType IN (1,2)) AS Titles,
        ///		   (select STRING_AGG(wt1.Title, &apos;, &apos;) from WorksTitle wt1 where wt1.WorksId = w.Id and wt1.TitleType IN (3,4)) AS AlternateTitles,
        ///		   w.ProductionYear, w.CompactRef, 
        ///		   rt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string V_ClientWorkListOfRights {
            get {
                return ResourceManager.GetString("V_ClientWorkListOfRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR ALTER VIEW [dbo].[V_ClientWorksList] AS
        ///select distinct  
        ///    cl.Id as ClientId, cl.ClientName, ct.Id as CatalogueId, ct.Name as CatalogueName,  
        ///    w.Id as WorksId, w.ProductionYear,  w.Discriminator,   
        ///    (select STRING_AGG(wt1.Title, &apos;, &apos;) from WorksTitle wt1 where wt1.WorksId = w.Id and wt1.TitleType IN (1,2)) AS Titles,  
        ///    (select STRING_AGG(wt1.Title, &apos;, &apos;) from WorksTitle wt1 where wt1.WorksId = w.Id and wt1.TitleType IN (3,4)) AS AlternateTitles,  
        ///    st.Title AS SeasonTitle,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string V_ClientWorksList {
            get {
                return ResourceManager.GetString("V_ClientWorksList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR ALTER VIEW [dbo].[V_ClientWorkStatsByProductionYear] AS
        ///WITH YEARLY_STATS AS (
        ///	SELECT
        ///		cw.ClientsId AS ClientId,
        ///		w.ProductionYear,
        ///		COUNT(CASE WHEN w.Discriminator = &apos;StandAlone&apos; THEN 1 END) AS StandAlones,
        ///		COUNT(CASE WHEN w.Discriminator = &apos;Series&apos; THEN 1 END) AS Series,
        ///		COUNT(CASE WHEN w.Discriminator = &apos;Episode&apos; THEN 1 END) AS Episodes,
        ///		COUNT(CASE WHEN w.Discriminator = &apos;Season&apos; THEN 1 END) AS Seasons
        ///	FROM ClientWorks cw
        ///	JOIN Works w ON cw.WorksId = w.Id
        ///	GROUP BY cw.Cli [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string V_ClientWorkStatsByProductionYear {
            get {
                return ResourceManager.GetString("V_ClientWorkStatsByProductionYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR ALTER VIEW [dbo].[V_ClientWorkYearlyStats] AS
        ///WITH YEARLY_STATS AS (
        ///	SELECT
        ///		cw.ClientsId AS ClientId,
        ///		DATEPART(YEAR, w.CreationDate) AS CreatedYear,
        ///		COUNT(CASE WHEN w.Discriminator = &apos;StandAlone&apos; THEN 1 END) AS StandAlones,
        ///		COUNT(CASE WHEN w.Discriminator = &apos;Series&apos; THEN 1 END) AS Series,
        ///		COUNT(CASE WHEN w.Discriminator = &apos;Episode&apos; THEN 1 END) AS Episodes,
        ///		COUNT(CASE WHEN w.Discriminator = &apos;Season&apos; THEN 1 END) AS Seasons
        ///	FROM ClientWorks cw
        ///	JOIN Works w ON cw.WorksId = w.I [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string V_ClientWorkYearlyStats {
            get {
                return ResourceManager.GetString("V_ClientWorkYearlyStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR ALTER VIEW [dbo].[V_WorksDetails]
        ///AS
        ///SELECT Id AS WorksId,
        ///                 (SELECT STRING_AGG(c.ClientName, &apos;, &apos;) AS Expr1
        ///                 FROM    dbo.Clients AS c INNER JOIN
        ///                              dbo.Catalogue AS cat ON cat.ClientId = c.Id INNER JOIN
        ///                              dbo.CatalogueWorks AS cw ON cw.CataloguesId = cat.Id
        ///                 WHERE (cw.WorksId = w.Id)) AS Client,
        ///                 (SELECT STRING_AGG(cat.Name, &apos;, &apos;) AS Expr1
        ///                 FROM    dbo.Cat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string V_WorksDetails {
            get {
                return ResourceManager.GetString("V_WorksDetails", resourceCulture);
            }
        }
    }
}
