using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Serialization;

namespace Oscar.Core.Schemas
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.42000
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------
    // 
    // This source code was auto-generated by xsd, Version=4.8.3928.0.
    // 

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class AgicoaWri
    {

        private DataHeader headerField;

        private DataWork[] workField;

        private DataFooter footerField;

        /// <remarks/>
        public DataHeader Header
        {
            get
            {
                return this.headerField;
            }
            set
            {
                this.headerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Work")]
        public DataWork[] Work
        {
            get
            {
                return this.workField;
            }
            set
            {
                this.workField = value;
            }
        }

        /// <remarks/>
        public DataFooter Footer
        {
            get
            {
                return this.footerField;
            }
            set
            {
                this.footerField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DataHeader
    {

        private string versionField;

        private string fromCompanyField;

        private string fromPersonField;

        private string toCompanyField;

        private string toPersonField;

        private string begDateField;

        private string begTimeField;

        private string extensionsField;

        /// <remarks/>
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        public string FromCompany
        {
            get
            {
                return this.fromCompanyField;
            }
            set
            {
                this.fromCompanyField = value;
            }
        }

        /// <remarks/>
        public string FromPerson
        {
            get
            {
                return this.fromPersonField;
            }
            set
            {
                this.fromPersonField = value;
            }
        }

        /// <remarks/>
        public string ToCompany
        {
            get
            {
                return this.toCompanyField;
            }
            set
            {
                this.toCompanyField = value;
            }
        }

        /// <remarks/>
        public string ToPerson
        {
            get
            {
                return this.toPersonField;
            }
            set
            {
                this.toPersonField = value;
            }
        }

        /// <remarks/>
        public string BegDate
        {
            get
            {
                return this.begDateField;
            }
            set
            {
                this.begDateField = value;
            }
        }

        /// <remarks/>
        public string BegTime
        {
            get
            {
                return this.begTimeField;
            }
            set
            {
                this.begTimeField = value;
            }
        }

        /// <remarks/>
        public string Extensions
        {
            get
            {
                return this.extensionsField;
            }
            set
            {
                this.extensionsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DataWork
    {

        private string wNSField;

        private string wNRField;

        private string slField;

        private string sNSField;

        private string sNRField;

        private string snNSField;

        private string snNRField;

        private string snNField;

        private string enField;

        private string tSEField;

        private string tEPField;

        private string dField;

        private string tField;

        private string kField;

        private string ypField;

        private string iField;

        private string wdField;

        private DataWorkTtl[] ttlsField;

        private string[] cntyPrdsField;

        private string[] olngsField;

        private DataWorkIPart[] iPartsField;

        private DataWorkCmpyPrd[] cmpyPrdsField;

        private DataWorkRgt[] rgtsField;

        private DataWorkMandate[] mandatesField;

        /// <remarks/>
        public string WNS
        {
            get
            {
                return this.wNSField;
            }
            set
            {
                this.wNSField = value;
            }
        }

        /// <remarks/>
        public string WNR
        {
            get
            {
                return this.wNRField;
            }
            set
            {
                this.wNRField = value;
            }
        }

        /// <remarks/>
        public string SL
        {
            get
            {
                return this.slField;
            }
            set
            {
                this.slField = value;
            }
        }

        /// <remarks/>
        public string SNS
        {
            get
            {
                return this.sNSField;
            }
            set
            {
                this.sNSField = value;
            }
        }

        /// <remarks/>
        public string SNR
        {
            get
            {
                return this.sNRField;
            }
            set
            {
                this.sNRField = value;
            }
        }

        /// <remarks/>
        public string SnNS
        {
            get
            {
                return this.snNSField;
            }
            set
            {
                this.snNSField = value;
            }
        }

        /// <remarks/>
        public string SnNR
        {
            get
            {
                return this.snNRField;
            }
            set
            {
                this.snNRField = value;
            }
        }

        /// <remarks/>
        public string SnN
        {
            get
            {
                return this.snNField;
            }
            set
            {
                this.snNField = value;
            }
        }

        /// <remarks/>
        public string EN
        {
            get
            {
                return this.enField;
            }
            set
            {
                this.enField = value;
            }
        }

        /// <remarks/>
        public string TSE
        {
            get
            {
                return this.tSEField;
            }
            set
            {
                this.tSEField = value;
            }
        }

        /// <remarks/>
        public string TEP
        {
            get
            {
                return this.tEPField;
            }
            set
            {
                this.tEPField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string D
        {
            get
            {
                return this.dField;
            }
            set
            {
                this.dField = value;
            }
        }

        /// <remarks/>
        public string T
        {
            get
            {
                return this.tField;
            }
            set
            {
                this.tField = value;
            }
        }

        /// <remarks/>
        public string K
        {
            get
            {
                return this.kField;
            }
            set
            {
                this.kField = value;
            }
        }

        /// <remarks/>
        public string YP
        {
            get
            {
                return this.ypField;
            }
            set
            {
                this.ypField = value;
            }
        }

        /// <remarks/>
        public string I
        {
            get
            {
                return this.iField;
            }
            set
            {
                this.iField = value;
            }
        }

        /// <remarks/>
        public string WD
        {
            get
            {
                return this.wdField;
            }
            set
            {
                this.wdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Ttl", IsNullable = false)]
        public DataWorkTtl[] Ttls
        {
            get
            {
                return this.ttlsField;
            }
            set
            {
                this.ttlsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("C", IsNullable = false)]
        public string[] CntyPrds
        {
            get
            {
                return this.cntyPrdsField;
            }
            set
            {
                this.cntyPrdsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("L", IsNullable = false)]
        public string[] Olngs
        {
            get
            {
                return this.olngsField;
            }
            set
            {
                this.olngsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("IPart", IsNullable = false)]
        public DataWorkIPart[] IParts
        {
            get
            {
                return this.iPartsField;
            }
            set
            {
                this.iPartsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("CmpyPrd", IsNullable = false)]
        public DataWorkCmpyPrd[] CmpyPrds
        {
            get
            {
                return this.cmpyPrdsField;
            }
            set
            {
                this.cmpyPrdsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Rgt", IsNullable = false)]
        public DataWorkRgt[] Rgts
        {
            get
            {
                return this.rgtsField;
            }
            set
            {
                this.rgtsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Mandate", IsNullable = false)]
        public DataWorkMandate[] Mandates
        {
            get
            {
                return this.mandatesField;
            }
            set
            {
                this.mandatesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DataWorkTtl
    {

        private string oField;

        private string lField;

        private string tField;

        /// <remarks/>
        public string O
        {
            get
            {
                return this.oField;
            }
            set
            {
                this.oField = value;
            }
        }

        /// <remarks/>
        public string L
        {
            get
            {
                return this.lField;
            }
            set
            {
                this.lField = value;
            }
        }

        /// <remarks/>
        public string T
        {
            get
            {
                return this.tField;
            }
            set
            {
                this.tField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DataWorkIPart
    {

        private string tField;

        private string lField;

        private string fField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string T
        {
            get
            {
                return this.tField;
            }
            set
            {
                this.tField = value;
            }
        }

        /// <remarks/>
        public string L
        {
            get
            {
                return this.lField;
            }
            set
            {
                this.lField = value;
            }
        }

        /// <remarks/>
        public string F
        {
            get
            {
                return this.fField;
            }
            set
            {
                this.fField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DataWorkCmpyPrd
    {

        private string tField;

        private string nField;

        private string oField;

        private string pField;

        public DataWorkCmpyPrd()
        {
            this.oField = "no";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string T
        {
            get
            {
                return this.tField;
            }
            set
            {
                this.tField = value;
            }
        }

        /// <remarks/>
        public string N
        {
            get
            {
                return this.nField;
            }
            set
            {
                this.nField = value;
            }
        }

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("no")]
        public string O
        {
            get
            {
                return this.oField;
            }
            set
            {
                this.oField = value;
            }
        }

        /// <remarks/>
        public string P
        {
            get
            {
                return this.pField;
            }
            set
            {
                this.pField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DataWorkRgt
    {

        private string rRSField;

        private string rNSField;

        private string rRRField;

        private string cField;

        private string lField;

        private string chField;

        private decimal pField;

        private bool pFieldSpecified;

        private string rfField;

        private string rtField;

        private string vfField;

        private string vtField;

        private string tField;

        public DataWorkRgt()
        {
            this.tField = "CA";
        }

        /// <remarks/>
        public string RRS
        {
            get
            {
                return this.rRSField;
            }
            set
            {
                this.rRSField = value;
            }
        }

        /// <remarks/>
        public string RNS
        {
            get
            {
                return this.rNSField;
            }
            set
            {
                this.rNSField = value;
            }
        }

        /// <remarks/>
        public string RRR
        {
            get
            {
                return this.rRRField;
            }
            set
            {
                this.rRRField = value;
            }
        }

        /// <remarks/>
        public string C
        {
            get
            {
                return this.cField;
            }
            set
            {
                this.cField = value;
            }
        }

        /// <remarks/>
        public string L
        {
            get
            {
                return this.lField;
            }
            set
            {
                this.lField = value;
            }
        }

        /// <remarks/>
        public string Ch
        {
            get
            {
                return this.chField;
            }
            set
            {
                this.chField = value;
            }
        }

        /// <remarks/>
        public decimal P
        {
            get
            {
                return this.pField;
            }
            set
            {
                this.pField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PSpecified
        {
            get
            {
                return this.pFieldSpecified;
            }
            set
            {
                this.pFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string RF
        {
            get
            {
                return this.rfField;
            }
            set
            {
                this.rfField = value;
            }
        }

        /// <remarks/>
        public string RT
        {
            get
            {
                return this.rtField;
            }
            set
            {
                this.rtField = value;
            }
        }

        /// <remarks/>
        public string VF
        {
            get
            {
                return this.vfField;
            }
            set
            {
                this.vfField = value;
            }
        }

        /// <remarks/>
        public string VT
        {
            get
            {
                return this.vtField;
            }
            set
            {
                this.vtField = value;
            }
        }

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("CA")]
        public string T
        {
            get
            {
                return this.tField;
            }
            set
            {
                this.tField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DataWorkMandate
    {

        private string tField;

        private string mField;

        /// <remarks/>
        public string T
        {
            get
            {
                return this.tField;
            }
            set
            {
                this.tField = value;
            }
        }

        /// <remarks/>
        public string M
        {
            get
            {
                return this.mField;
            }
            set
            {
                this.mField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DataFooter
    {

        private string recCountField;

        private string endDateField;

        private string endTimeField;

        private string extensionsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string RecCount
        {
            get
            {
                return this.recCountField;
            }
            set
            {
                this.recCountField = value;
            }
        }

        /// <remarks/>
        public string EndDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                this.endDateField = value;
            }
        }

        /// <remarks/>
        public string EndTime
        {
            get
            {
                return this.endTimeField;
            }
            set
            {
                this.endTimeField = value;
            }
        }

        /// <remarks/>
        public string Extensions
        {
            get
            {
                return this.extensionsField;
            }
            set
            {
                this.extensionsField = value;
            }
        }
    }

}
