// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oscar.Mrit.Data;

#nullable disable

namespace Oscar.Mrit.Migrations
{
    [DbContext(typeof(FelixMritContext))]
    partial class FelixMritContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AltProductionTitleMatch", b =>
                {
                    b.Property<int>("AltProductionTitlesId")
                        .HasColumnType("int");

                    b.Property<int>("MatchesId")
                        .HasColumnType("int");

                    b.HasKey("AltProductionTitlesId", "MatchesId");

                    b.HasIndex("MatchesId");

                    b.ToTable("AltProductionTitleMatch");
                });

            modelBuilder.Entity("AltRecordTitleMatch", b =>
                {
                    b.Property<int>("AltRecordTitlesId")
                        .HasColumnType("int");

                    b.Property<int>("MatchesId")
                        .HasColumnType("int");

                    b.HasKey("AltRecordTitlesId", "MatchesId");

                    b.HasIndex("MatchesId");

                    b.ToTable("AltRecordTitleMatch");
                });

            modelBuilder.Entity("CompanyMatch", b =>
                {
                    b.Property<int>("CompaniesId")
                        .HasColumnType("int");

                    b.Property<int>("MatchesId")
                        .HasColumnType("int");

                    b.HasKey("CompaniesId", "MatchesId");

                    b.HasIndex("MatchesId");

                    b.ToTable("CompanyMatch");
                });

            modelBuilder.Entity("CountryMatch", b =>
                {
                    b.Property<int>("CountriesId")
                        .HasColumnType("int");

                    b.Property<int>("MatchesId")
                        .HasColumnType("int");

                    b.HasKey("CountriesId", "MatchesId");

                    b.HasIndex("MatchesId");

                    b.ToTable("CountryMatch");
                });

            modelBuilder.Entity("GenreMatch", b =>
                {
                    b.Property<int>("GenresId")
                        .HasColumnType("int");

                    b.Property<int>("MatchesId")
                        .HasColumnType("int");

                    b.HasKey("GenresId", "MatchesId");

                    b.HasIndex("MatchesId");

                    b.ToTable("GenreMatch");
                });

            modelBuilder.Entity("LanguageMatch", b =>
                {
                    b.Property<int>("LanguagesId")
                        .HasColumnType("int");

                    b.Property<int>("MatchesId")
                        .HasColumnType("int");

                    b.HasKey("LanguagesId", "MatchesId");

                    b.HasIndex("MatchesId");

                    b.ToTable("LanguageMatch");
                });

            modelBuilder.Entity("MatchPersonOfInterest", b =>
                {
                    b.Property<int>("MatchesId")
                        .HasColumnType("int");

                    b.Property<int>("PersonOfInterestsId")
                        .HasColumnType("int");

                    b.HasKey("MatchesId", "PersonOfInterestsId");

                    b.HasIndex("PersonOfInterestsId");

                    b.ToTable("MatchPersonOfInterest");
                });

            modelBuilder.Entity("MatchWorks", b =>
                {
                    b.Property<int>("MatchesId")
                        .HasColumnType("int");

                    b.Property<int>("WorksId")
                        .HasColumnType("int");

                    b.HasKey("MatchesId", "WorksId");

                    b.HasIndex("WorksId");

                    b.ToTable("MatchWorks");
                });

            modelBuilder.Entity("Oscar.Mrit.Data.AltProductionTitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AltProductionTitle");
                });

            modelBuilder.Entity("Oscar.Mrit.Data.AltRecordTitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AltRecordTitles");
                });

            modelBuilder.Entity("Oscar.Mrit.Data.BatchJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid>("BatchJobKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BatchJobs");
                });

            modelBuilder.Entity("Oscar.Mrit.Data.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SimpleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Oscar.Mrit.Data.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Alpha2Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Alpha3Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumericCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Oscar.Mrit.Data.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("Oscar.Mrit.Data.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EnglishName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrenchName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GermanName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISO639_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISO639_2")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("Oscar.Mrit.Data.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("BatchJobId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EpisodeNumber")
                        .HasColumnType("int");

                    b.Property<int>("ProductionId")
                        .HasColumnType("int");

                    b.Property<string>("ProductionTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductionYear")
                        .HasColumnType("int");

                    b.Property<int>("RecordId")
                        .HasColumnType("int");

                    b.Property<string>("RecordTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SeasonNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BatchJobId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Oscar.Mrit.Data.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Forename")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleNames")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SimpleName")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("Oscar.Mrit.Data.PersonOfInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<int?>("PersonTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("PersonTypeId");

                    b.ToTable("PersonsOfInterest");
                });

            modelBuilder.Entity("Oscar.Mrit.Data.PersonType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PersonTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2024, 11, 16, 12, 19, 23, 488, DateTimeKind.Local).AddTicks(8194),
                            Name = "Director"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2024, 11, 16, 12, 19, 23, 488, DateTimeKind.Local).AddTicks(8258),
                            Name = "Actor"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2024, 11, 16, 12, 19, 23, 488, DateTimeKind.Local).AddTicks(8262),
                            Name = "Producer"
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2024, 11, 16, 12, 19, 23, 488, DateTimeKind.Local).AddTicks(8264),
                            Name = "Creator"
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2024, 11, 16, 12, 19, 23, 488, DateTimeKind.Local).AddTicks(8268),
                            Name = "Writer"
                        });
                });

            modelBuilder.Entity("Oscar.Mrit.Data.Territory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Territories");
                });

            modelBuilder.Entity("Oscar.Mrit.Data.Transmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BroadcastDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("BroadcastDuration")
                        .HasColumnType("int");

                    b.Property<string>("BroadcastLanguage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Channel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MatchId")
                        .HasColumnType("int");

                    b.Property<int>("MritId")
                        .HasColumnType("int");

                    b.Property<string>("TransmissionEpisodeTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransmissionProductionTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("MritId")
                        .IsUnique();

                    b.ToTable("Transmissions");
                });

            modelBuilder.Entity("Oscar.Mrit.Data.Works", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorksId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Works");
                });

            modelBuilder.Entity("TerritoryTransmission", b =>
                {
                    b.Property<int>("TerritoriesId")
                        .HasColumnType("int");

                    b.Property<int>("TransmissionsId")
                        .HasColumnType("int");

                    b.HasKey("TerritoriesId", "TransmissionsId");

                    b.HasIndex("TransmissionsId");

                    b.ToTable("TerritoryTransmission");
                });

            modelBuilder.Entity("AltProductionTitleMatch", b =>
                {
                    b.HasOne("Oscar.Mrit.Data.AltProductionTitle", null)
                        .WithMany()
                        .HasForeignKey("AltProductionTitlesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oscar.Mrit.Data.Match", null)
                        .WithMany()
                        .HasForeignKey("MatchesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AltRecordTitleMatch", b =>
                {
                    b.HasOne("Oscar.Mrit.Data.AltRecordTitle", null)
                        .WithMany()
                        .HasForeignKey("AltRecordTitlesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oscar.Mrit.Data.Match", null)
                        .WithMany()
                        .HasForeignKey("MatchesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CompanyMatch", b =>
                {
                    b.HasOne("Oscar.Mrit.Data.Company", null)
                        .WithMany()
                        .HasForeignKey("CompaniesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oscar.Mrit.Data.Match", null)
                        .WithMany()
                        .HasForeignKey("MatchesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CountryMatch", b =>
                {
                    b.HasOne("Oscar.Mrit.Data.Country", null)
                        .WithMany()
                        .HasForeignKey("CountriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oscar.Mrit.Data.Match", null)
                        .WithMany()
                        .HasForeignKey("MatchesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenreMatch", b =>
                {
                    b.HasOne("Oscar.Mrit.Data.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oscar.Mrit.Data.Match", null)
                        .WithMany()
                        .HasForeignKey("MatchesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LanguageMatch", b =>
                {
                    b.HasOne("Oscar.Mrit.Data.Language", null)
                        .WithMany()
                        .HasForeignKey("LanguagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oscar.Mrit.Data.Match", null)
                        .WithMany()
                        .HasForeignKey("MatchesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MatchPersonOfInterest", b =>
                {
                    b.HasOne("Oscar.Mrit.Data.Match", null)
                        .WithMany()
                        .HasForeignKey("MatchesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oscar.Mrit.Data.PersonOfInterest", null)
                        .WithMany()
                        .HasForeignKey("PersonOfInterestsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MatchWorks", b =>
                {
                    b.HasOne("Oscar.Mrit.Data.Match", null)
                        .WithMany()
                        .HasForeignKey("MatchesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oscar.Mrit.Data.Works", null)
                        .WithMany()
                        .HasForeignKey("WorksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Oscar.Mrit.Data.Match", b =>
                {
                    b.HasOne("Oscar.Mrit.Data.BatchJob", "BatchJob")
                        .WithMany("Matches")
                        .HasForeignKey("BatchJobId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("BatchJob");
                });

            modelBuilder.Entity("Oscar.Mrit.Data.PersonOfInterest", b =>
                {
                    b.HasOne("Oscar.Mrit.Data.Person", "Person")
                        .WithMany("PersonOfInterests")
                        .HasForeignKey("PersonId");

                    b.HasOne("Oscar.Mrit.Data.PersonType", "PersonType")
                        .WithMany("PersonOfInterests")
                        .HasForeignKey("PersonTypeId");

                    b.Navigation("Person");

                    b.Navigation("PersonType");
                });

            modelBuilder.Entity("Oscar.Mrit.Data.Transmission", b =>
                {
                    b.HasOne("Oscar.Mrit.Data.Match", "Match")
                        .WithMany("Transmissions")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Match");
                });

            modelBuilder.Entity("TerritoryTransmission", b =>
                {
                    b.HasOne("Oscar.Mrit.Data.Territory", null)
                        .WithMany()
                        .HasForeignKey("TerritoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oscar.Mrit.Data.Transmission", null)
                        .WithMany()
                        .HasForeignKey("TransmissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Oscar.Mrit.Data.BatchJob", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("Oscar.Mrit.Data.Match", b =>
                {
                    b.Navigation("Transmissions");
                });

            modelBuilder.Entity("Oscar.Mrit.Data.Person", b =>
                {
                    b.Navigation("PersonOfInterests");
                });

            modelBuilder.Entity("Oscar.Mrit.Data.PersonType", b =>
                {
                    b.Navigation("PersonOfInterests");
                });
#pragma warning restore 612, 618
        }
    }
}
